# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
- name: tag
  type: string
  default: 'imadelfetouh99/kwetterfrontend'

trigger:
- main

resources:
- repo: self

variables:
  tag: 'imadelfetouh99/kwetterfrontend'
  imageName: 'imadelfetouh99/kwetterfrontend'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/kwetterfrontend/Dockerfile'
        tags: '${{ parameters.tag }}'

    - task: Docker@2
      inputs:
        containerRegistry: 'dockerregistry'
        repository: 'imadelfetouh99/kwetterfrontend'
        command: 'push'
        

