trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistry'
    repository: 'imadelfetouh99/kwetterfrontend'
    command: 'buildAndPush'
    Dockerfile: 'docker/Dockerfile'
    buildContext: 
    tags: 'latest'