apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetterfrontend-deployment
  labels:
    app: kwetterfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwetterfrontend
  template:
    metadata:
      labels:
        app: kwetterfrontend
    spec:
      containers:
        - name: kwetterfrontend
          imagePullPolicy: Always
          image: imadelfetouh99/kwetterfrontend:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: kwetterfrontend-service
spec:
  selector:
    app: kwetterfrontend
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000